### ISSUE TITLE
Todo #1

### ISSUE THREAD

**Issue by Adoria298** [Adoria298/flask-messenger#2]
**Todo list for WC:2018-03-05.**

- [x] Add/Choose a licence
- [x] Change order of messages so the most recent are first
- [x] Start work on implementing a login system.

**Comment by Adoria298** [comment]
Login system has already been partially implemented, so part 3 is closed.

**Comment by Adoria298** [comment]
Added the GNU GPLv3 licence.
