### ISSUE TITLE
todo #2

### ISSUE THREAD

**Issue by Adoria298** [Adoria298/flask-messenger#5]
Todo List for WC: 12/3/18

- [x] Implement username checking login system.
- [ ] Set up different pages per user.
- [ ] Add css/layout to `login.html`

**Comment by Adoria298** [comment]
Different pages per user could be implemented like this:
`users = {"Adoria298":  {"pages" : ["home", "view", "admin"] } }`
`hello(messages, users["Adoria298"]["pages"])`

This would tell jinja2 that the pages (in navigation) to use are those of Adoria298.

**Comment by Adoria298** [comment]
A new roadmap for flask-messenger will allow the login system, and different pages per user, to be implemented much more easily and efficiently. As such, this todo item has been closed, and a new todo will appear when the roadmap is finalised.

**Comment by Adoria298** [comment]
New todos will be managed in projects.
